In [183]:
# First Import the Pandas, pathlib, & Numpy Packages

import pandas as pd
import numpy as np
import pathlib

In [184]:
# Set Up Export and Export Paths
root_path = r'C:\Users\MLeif\data_science_practice'
project_folder = '1_descriptive_stats'
data_folder = 'datasets'

import_path = pathlib.Path(root_path).joinpath(project_folder).joinpath(data_folder)
export_path = pathlib.Path(root_path).joinpath(project_folder).joinpath(data_folder)

print(import_path)
print(export_path)

C:\Users\MLeif\data_science_practice\1_descriptive_stats\datasets
C:\Users\MLeif\data_science_practice\1_descriptive_stats\datasets

In [185]:
#Import the cleaned Film Dataset
import_data_file = 'imdb_film_clean.csv'
import_file = import_path.joinpath(import_data_file)

imdb_movies = pd.read_csv(import_file).drop_duplicates()
imdb_movies['movie_id'] = imdb_movies.index
imdb_movies = imdb_movies.set_index('movie_id')
imdb_movies.head()

,film_name,release_year,avg_score,total_votes,film_duration,genre_list,age_rating,age_rating_num,nudity_level,violence_level,...,genre_musical,genre_mystery,genre_news,genre_romance,genre_sci-fi,genre_short,genre_sport,genre_thriller,genre_war,genre_western
movie_id,,,,,,,,,,,,,,,,,,,,,
0,spectre,2015,6.8,407514.0,148.0,"['action', ' adventure', ' thriller']",PG-13,3.0,1.0,2.0,...,0,0,0,0,0,0,0,1,0,0
1,casino royale,2006,8.0,613873.0,144.0,"['action', ' adventure', ' thriller']",PG-13,3.0,1.0,2.0,...,0,0,0,0,0,0,0,1,0,0
2,the night house,2020,6.5,14936.0,107.0,"['horror', ' mystery', ' thriller']",R,4.0,1.0,2.0,...,0,1,0,0,0,0,0,1,0,0
3,venom,2018,6.7,414787.0,112.0,"['action', ' adventure', ' sci-fi']",PG-13,3.0,1.0,2.0,...,0,0,0,0,1,0,0,0,0,0
4,skyfall,2012,7.8,658977.0,143.0,"['action', ' adventure', ' thriller']",PG-13,3.0,1.0,2.0,...,0,0,0,0,0,0,0,1,0,0

In [74]:
imdb_movies.shape

(3130, 37)

In [75]:
imdb_movies.isnull().sum()

film_name              0
release_year           0
avg_score             15
total_votes            0
film_duration         15
genre_list             0
age_rating           274
age_rating_num       274
nudity_level          79
violence_level        78
profanity_level       82
alcohol_level         88
frightening_level     93
genre_action           0
genre_adventure        0
genre_animation        0
genre_biography        0
genre_comedy           0
genre_crime            0
genre_documentary      0
genre_drama            0
genre_family           0
genre_fantasy          0
genre_film-noir        0
genre_history          0
genre_horror           0
genre_music            0
genre_musical          0
genre_mystery          0
genre_news             0
genre_romance          0
genre_sci-fi           0
genre_short            0
genre_sport            0
genre_thriller         0
genre_war              0
genre_western          0
dtype: int64

In [76]:
imdb_movies.dtypes

film_name             object
release_year           int64
avg_score            float64
total_votes          float64
film_duration        float64
genre_list            object
age_rating            object
age_rating_num       float64
nudity_level         float64
violence_level       float64
profanity_level      float64
alcohol_level        float64
frightening_level    float64
genre_action           int64
genre_adventure        int64
genre_animation        int64
genre_biography        int64
genre_comedy           int64
genre_crime            int64
genre_documentary      int64
genre_drama            int64
genre_family           int64
genre_fantasy          int64
genre_film-noir        int64
genre_history          int64
genre_horror           int64
genre_music            int64
genre_musical          int64
genre_mystery          int64
genre_news             int64
genre_romance          int64
genre_sci-fi           int64
genre_short            int64
genre_sport            int64
genre_thriller         int64
genre_war              int64
genre_western          int64
dtype: object

In [106]:
#Question 1: What are the top 20 Films with the Most Votes

top_20_movies = imdb_movies.sort_values('total_votes',ascending=False).head(20)

print(str(top_20_movies[['film_name','total_votes']]))

                                                  film_name  total_votes
movie_id
23                                 the shawshank redemption    2474122.0
45                                          the dark knight    2428117.0
60                                                inception    2178860.0
67                                               fight club    1948261.0
62                                             pulp fiction    1915230.0
99                                             forrest gump    1912582.0
21                                               the matrix    1767660.0
69        the lord of the rings: the fellowship of the ring    1736338.0
290           the lord of the rings: the return of the king    1715063.0
36                                            the godfather    1709439.0
40                                             interstellar    1624116.0
158                                   the dark knight rises    1583199.0
491                   the lord of the rings: the two towers    1550497.0
133                                                   se7en    1522727.0
74                                         django unchained    1432853.0
34                                                gladiator    1403705.0
387                                           batman begins    1364161.0
91                                     inglourious basterds    1338008.0
78                                 the silence of the lambs    1336681.0
303                                            the avengers    1311358.0

In [78]:
# Create a subset of columns with only Genre Columns

genere_list = ['genre_action','genre_adventure','genre_western',
       'genre_animation','genre_biography','genre_comedy','genre_crime',
       'genre_documentary','genre_drama','genre_family','genre_fantasy',
       'genre_film-noir','genre_history','genre_horror','genre_music',
       'genre_musical','genre_mystery','genre_romance','genre_sci-fi',
       'genre_short','genre_sport','genre_thriller','genre_war']

genre_col = ['movie_id'] + [genere_list]

movie_genre = imdb_movies[genere_list]

In [79]:
# For the Next Few Questions Create a Dataset of Just Genre Flags

genre_melt = movie_genre.reset_index().melt(id_vars=['movie_id'], value_vars=[
       'genre_action','genre_adventure','genre_western',
       'genre_animation','genre_biography','genre_comedy','genre_crime',
       'genre_documentary','genre_drama','genre_family','genre_fantasy',
       'genre_film-noir','genre_history','genre_horror','genre_music',
       'genre_musical','genre_mystery','genre_romance','genre_sci-fi',
       'genre_short','genre_sport','genre_thriller','genre_war'
       ]).\
       set_index('movie_id').\
       rename(columns = {'variable':'genre'}).\
       sort_values('genre', ascending=True)

genre_melt = genre_melt[genre_melt['value'] == 1].drop('value', axis=1)
genre_melt['genre'] = genre_melt['genre'].str.replace('genre_','')

genre_melt.head()

In [261]:
#Question 2: How Many Films are in Each Genre

movie_genre_totals = pd.DataFrame(genre_melt['genre'].value_counts()).reset_index().\
    rename(columns = {'index':'genre','genre':'Total_Films'})

print(movie_genre_totals)

          genre  Total_Films
0         drama         1495
1        comedy          956
2        action          929
3     adventure          741
4      thriller          612
5        horror          568
6         crime          536
7       romance          417
8       mystery          365
9        sci-fi          365
10      fantasy          326
11    biography          192
12       family          167
13    animation          144
14      history           96
15        music           61
16        sport           47
17          war           45
18      western           36
19      musical           29
20        short           10
21    film-noir            5
22  documentary            1

In [262]:
# Question 3: What are the Top 5 and Bottom 5 Film Genres

top_5_genres = movie_genre_totals['genre'].head(5)
bottom_5_genres = movie_genre_totals['genre'].tail(5)

print('Top 5 Film Genres: \n' + str(top_5_genres) + '\n')
print('Bottom 5 Film Genres: \n' + str(bottom_5_genres))

Top 5 Film Genres:
0        drama
1       comedy
2       action
3    adventure
4     thriller
Name: genre, dtype: object

Bottom 5 Film Genres:
18        western
19        musical
20          short
21      film-noir
22    documentary
Name: genre, dtype: object

In [263]:
# Question 4: What are the top 10 Different Genre Combinations

genre_string = genre_melt.reset_index().\
    groupby(['movie_id'])['genre'].\
    apply(lambda x: '_'.join(x)).reset_index()

multi_genre = genre_string[genre_string['genre'].str.contains('_')]

top_genre_combos = pd.DataFrame(multi_genre.reset_index().\
    groupby('genre')['movie_id'].count()).\
    sort_values('movie_id', ascending = False).\
    rename(columns = {'movie_id':'total_movies'}).iloc[0:10]

print(top_genre_combos)

                            total_movies
genre
action_adventure_sci-fi              111
drama_romance                        106
comedy_drama_romance                  94
adventure_animation_comedy            87
comedy_romance                        74
action_adventure_fantasy              72
horror_thriller                       70
action_crime_drama                    69
horror_mystery_thriller               66
action_adventure_comedy               66

In [334]:
# What is the Median and Percentile Number of Vores for each Film

votes_by_genre = imdb_movies[['total_votes']].join(genre_melt)

genre_votes_summary = votes_by_genre.groupby('genre')['total_votes'].\
    agg([np.mean, np.std, np.median])

genre_votes_summary = genre_votes_summary.join(votes_by_genre.groupby('genre').quantile(.10).\
    sort_values('total_votes', ascending=False).\
    rename(columns={'total_votes':'10_pct'}))

genre_votes_summary = genre_votes_summary.join(votes_by_genre.groupby('genre').quantile(.25).\
    sort_values('total_votes', ascending=False).\
    rename(columns={'total_votes':'25_pct'}))

genre_votes_summary = genre_votes_summary.join(votes_by_genre.groupby('genre').quantile(.75).\
    sort_values('total_votes', ascending=False).\
    rename(columns={'total_votes':'75_pct'}))

genre_votes_summary = genre_votes_summary.join(votes_by_genre.groupby('genre').quantile(.90).\
    sort_values('total_votes', ascending=False).\
    rename(columns={'total_votes':'90_pct'}))

print('Top 5 Genres with the Highest Mean Votes: ' + str(genre_votes_summary.sort_values('mean')['mean'].tail(5)))
print('Top 5 Genres with the Highest Median Votes: ' + str(genre_votes_summary.sort_values('median')['median'].tail(5)))
print('Top 5 Genres with the Highest Stdev of votes: ' + str(genre_votes_summary.sort_values('std')['std'].tail(5)))
print('Top 5 Genres with the Highest Mean Votes: ' + str(genre_votes_summary.sort_values('mean')['mean'].head(5)))
print('Top 5 Genres with the Highest Median Votes: ' + str(genre_votes_summary.sort_values('median')['median'].head(5)))
print('Top 5 Genres with the Highest Stdev of votes: ' + str(genre_votes_summary.sort_values('std')['std'].head(5)))

Top 5 Genres with the Highest Mean Votes: genre
action       243239.638321
animation    245537.743056
war          246232.000000
adventure    265537.188934
sci-fi       273172.682192
Name: mean, dtype: float64
Top 5 Genres with the Highest Median Votes: genre
film-noir    150448.0
action       167239.0
adventure    176676.0
animation    177854.5
sci-fi       177967.0
Name: median, dtype: float64
Top 5 Genres with the Highest Stdev of votes: genre
action         260310.161629
adventure      273741.197174
sci-fi         287820.665889
war            303822.530186
documentary              NaN
Name: std, dtype: float64
Top 5 Genres with the Highest Mean Votes: genre
short            3227.000000
documentary      9495.000000
horror          94750.964789
film-noir      109227.000000
musical        126421.379310
Name: mean, dtype: float64
Top 5 Genres with the Highest Median Votes: genre
short           2369.5
documentary     9495.0
horror         60262.0
western        79002.0
romance        86680.0
Name: median, dtype: float64
Top 5 Genres with the Highest Stdev of votes: genre
short          3064.507211
film-noir     89886.468843
musical      102380.916989
horror       106177.253551
music        163080.769115
Name: std, dtype: float64

In [332]:
duration_by_genre = imdb_movies[['film_duration']].join(genre_melt)

genre_duration_summary = duration_by_genre.groupby('genre')['film_duration'].\
    agg([np.mean, np.std, np.median])

genre_duration_summary = genre_duration_summary.join(duration_by_genre.groupby('genre').quantile(.10).\
    sort_values('film_duration', ascending=False).\
    rename(columns={'film_duration':'10_pct'}))

genre_duration_summary = genre_duration_summary.join(duration_by_genre.groupby('genre').quantile(.25).\
    sort_values('film_duration', ascending=False).\
    rename(columns={'film_duration':'25_pct'}))

genre_duration_summary = genre_duration_summary.join(duration_by_genre.groupby('genre').quantile(.75).\
    sort_values('film_duration', ascending=False).\
    rename(columns={'film_duration':'75_pct'}))

genre_duration_summary = genre_duration_summary.join(duration_by_genre.groupby('genre').quantile(.90).\
    sort_values('film_duration', ascending=False).\
    rename(columns={'film_duration':'90_pct'}))

print('Top 5 Genres with the Highest Mean duration: ' + str(genre_duration_summary.sort_values('mean')['mean'].tail(5)))
print('Top 5 Genres with the Shortest Mean duration: ' + str(genre_duration_summary.sort_values('mean')['mean'].head(5)))
print('Top 5 Genres with the Highest Median duration: ' + str(genre_duration_summary.sort_values('median')['median'].tail(5)))
print('Top 5 Genres with the Shortest Median duration: ' + str(genre_duration_summary.sort_values('median')['median'].head(5)))
print('Top 5 Genres with the Highest Stdev of duration: ' + str(genre_duration_summary.sort_values('std')['std'].tail(5)))
print('Top 5 Genres with the Lowest Stdev of duration: ' + str(genre_duration_summary.sort_values('std')['std'].head(5)))

Top 5 Genres with the Highest Mean duration: genre
drama        118.059021
western      125.750000
biography    128.450262
war          128.933333
history      137.864583
Name: mean, dtype: float64
Top 5 Genres with the Shortest Mean duration: genre
documentary    13.000000
short          17.500000
animation      95.562500
film-noir      98.600000
horror         99.602837
Name: mean, dtype: float64
Top 5 Genres with the Highest Median duration: genre
action       115.0
biography    124.0
western      125.0
war          127.0
history      134.0
Name: median, dtype: float64
Top 5 Genres with the Shortest Median duration: genre
documentary     13.0
short           17.5
animation       95.0
horror          97.0
film-noir      100.0
Name: median, dtype: float64
Top 5 Genres with the Highest Stdev of duration: genre
drama          22.697054
biography      23.600767
war            27.074309
history        27.968260
documentary          NaN
Name: std, dtype: float64
Top 5 Genres with the Lowest Stdev of duration: genre
film-noir    11.171392
short        11.404190
animation    13.295837
comedy       14.321836
horror       15.442153
Name: std, dtype: float64